/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and dependency check
         * @description Returns 200 when the process is up and Postgres answers, 503 otherwise. The body is the same shape either way.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the catalogue
         * @description Books in catalogue order, which is also the browse order.
         */
        get: operations["BooksController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one book
         * @description Resolves the book by UCI or slug and adds its row counts.
         */
        get: operations["BooksController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/{uci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a page by UCI
         * @description Returns the page body plus the UCIs of its neighbours, which is everything a reader needs to page forwards and backwards.
         */
        get: operations["PagesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a book's pages
         * @description The page index in printed order. Summaries only — `html` is not included; fetch a page individually for its body.
         */
        get: operations["BookPagesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/pages/{pageNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a page by its printed number
         * @description The citation-shaped lookup: "volume 2, page 26". `pageNo` is the printed number, not a 1-based offset.
         */
        get: operations["BookPagesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toc/{uci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a TOC entry
         * @description The entry with its enclosing chapter and, for a chapter, the fatwa titles it contains.
         */
        get: operations["TocController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/toc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a book's table of contents
         * @description Chapters in reading order, each with its fatwa titles nested underneath. Returned whole — the largest book has 2,067 entries and the payload is titles only.
         */
        get: operations["BookTocController_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/toc/flat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a book's table of contents as a flat list
         * @description The same entries in reading order without nesting, for clients that would rather walk the list than the tree. Use `level` and `parentUci` to recover the hierarchy.
         */
        get: operations["BookTocController_flat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health_Output: {
            /**
             * @description `ok` only when every dependency below is reachable. Served with 503 when it is `error`, so a probe can ignore the body entirely.
             * @enum {string}
             */
            status: "ok" | "error";
            /** @description Whole seconds since the process started. */
            uptime: number;
            /**
             * @description Result of a `select 1` against the Postgres pool.
             * @enum {string}
             */
            db: "up" | "down";
        };
        Book_Output: {
            /**
             * @description Immutable identifier, `BF<number>`. Frozen on publish — never renamed or renumbered.
             * @example BF11
             */
            uci: string;
            /**
             * @description Catalogue order, which is also the browse order. Volume sets are consecutive.
             * @example 11
             */
            number: number;
            /**
             * @description Human-readable handle. Renameable — the UCI is not.
             * @example fatawa-islamia-jild-2
             */
            slug: string;
            /** @description Title as printed, in Urdu. */
            title: string;
            /** @description Attribution verbatim from the source. Free text: multi-author books put several names in one string, and one scholar may be spelled differently across books. Not a stable key for grouping. */
            writer: string | null;
            publisher: string | null;
        };
        PaginatedBooks_Output: {
            items: components["schemas"]["Book_Output"][];
            total: number;
            limit: number;
            offset: number;
        };
        ValidationError: {
            /** @enum {number} */
            statusCode: 400;
            /** @enum {string} */
            message: "Validation failed";
            errors?: unknown[];
        };
        BookDetail_Output: {
            /**
             * @description Immutable identifier, `BF<number>`. Frozen on publish — never renamed or renumbered.
             * @example BF11
             */
            uci: string;
            /**
             * @description Catalogue order, which is also the browse order. Volume sets are consecutive.
             * @example 11
             */
            number: number;
            /**
             * @description Human-readable handle. Renameable — the UCI is not.
             * @example fatawa-islamia-jild-2
             */
            slug: string;
            /** @description Title as printed, in Urdu. */
            title: string;
            /** @description Attribution verbatim from the source. Free text: multi-author books put several names in one string, and one scholar may be spelled differently across books. Not a stable key for grouping. */
            writer: string | null;
            publisher: string | null;
            pageCount: number;
            tocEntryCount: number;
        };
        ApiError: {
            statusCode: number;
            message: string;
            error?: string;
        };
        PageDetail_Output: {
            /**
             * @description Composite: `BP` + book number + the printed page zero-padded to 4 digits. Parse right-to-left — the last four digits are always the page.
             * @example BP110026
             */
            uci: string;
            /** @example BF11 */
            bookUci: string;
            /**
             * @description The REAL PRINTED page number, not a 1-based offset — books in this corpus start anywhere from page 1 to page 179. This is the citation and half of the UCI.
             * @example 26
             */
            pageNo: number;
            /** @description The page body as an HTML fragment. Presentation is encoded as a fixed class vocabulary: `lu` `la` `le` `lx` (language: Urdu, Arabic, English, unspecified), `b` `i` `u` `hl` (bold, italic, underline, highlight), `fn` (footnote marker), `tc` `tj` `ta0` `ta3` (alignment), `s12`–`s26` (font size in pt). Note `u` (underline) and `lu` (Urdu) are distinct tokens. WARNING: the markup is stored exactly as it came from the source — 1,264 pages contain unbalanced `<span>` tags, so parse defensively rather than assuming a well-formed tree. */
            html: string;
            /** @description The page's footnote block; may be absent. */
            footnotes: string | null;
            /** @description Previous page in this book, or null at the start. */
            prevUci: string | null;
            /** @description Next page in this book, or null at the end. */
            nextUci: string | null;
        };
        PageSummary_Output: {
            /** @example BP110026 */
            uci: string;
            /**
             * @description The REAL PRINTED page number, not a 1-based offset — books in this corpus start anywhere from page 1 to page 179. This is the citation and half of the UCI.
             * @example 26
             */
            pageNo: number;
            hasFootnotes: boolean;
        };
        PaginatedPageSummaries_Output: {
            items: components["schemas"]["PageSummary_Output"][];
            total: number;
            limit: number;
            offset: number;
        };
        TocEntry_Output: {
            /**
             * @description Composite: `BT` + book number + the entry number zero-padded to 4 digits.
             * @example BT110001
             */
            uci: string;
            /** @example BF11 */
            bookUci: string;
            /** @description Reading order within the book, 1-based. */
            numberInBook: number;
            /** @description 1 = chapter, 2 = fatwa title. */
            level: 1 | 2;
            /** @description The enclosing chapter's UCI; null for a chapter itself. */
            parentUci: string | null;
            /** @description Heading text. A source row with a blank heading is stored as '—' rather than being given invented text. */
            title: string;
            /**
             * @description The page this entry points at.
             * @example BP110026
             */
            pageUci: string;
            /**
             * @description The printed page number, read straight out of `pageUci` — a citation needs no extra request.
             * @example 26
             */
            pageNo: number;
        };
        TocEntryDetail_Output: {
            /**
             * @description Composite: `BT` + book number + the entry number zero-padded to 4 digits.
             * @example BT110001
             */
            uci: string;
            /** @example BF11 */
            bookUci: string;
            /** @description Reading order within the book, 1-based. */
            numberInBook: number;
            /** @description 1 = chapter, 2 = fatwa title. */
            level: 1 | 2;
            /** @description The enclosing chapter's UCI; null for a chapter itself. */
            parentUci: string | null;
            /** @description Heading text. A source row with a blank heading is stored as '—' rather than being given invented text. */
            title: string;
            /**
             * @description The page this entry points at.
             * @example BP110026
             */
            pageUci: string;
            /**
             * @description The printed page number, read straight out of `pageUci` — a citation needs no extra request.
             * @example 26
             */
            pageNo: number;
            parent: components["schemas"]["TocEntry_Output"] | null;
            children: components["schemas"]["TocEntry_Output"][];
        };
        TocChapter_Output: {
            /**
             * @description Composite: `BT` + book number + the entry number zero-padded to 4 digits.
             * @example BT110001
             */
            uci: string;
            /** @example BF11 */
            bookUci: string;
            /** @description Reading order within the book, 1-based. */
            numberInBook: number;
            /** @description 1 = chapter, 2 = fatwa title. */
            level: 1 | 2;
            /** @description The enclosing chapter's UCI; null for a chapter itself. */
            parentUci: string | null;
            /** @description Heading text. A source row with a blank heading is stored as '—' rather than being given invented text. */
            title: string;
            /**
             * @description The page this entry points at.
             * @example BP110026
             */
            pageUci: string;
            /**
             * @description The printed page number, read straight out of `pageUci` — a citation needs no extra request.
             * @example 26
             */
            pageNo: number;
            children: components["schemas"]["TocEntry_Output"][];
        };
        TocTree_Output: components["schemas"]["TocChapter_Output"][];
        TocFlat_Output: components["schemas"]["TocEntry_Output"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Everything is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health_Output"];
                };
            };
            /** @description A dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health_Output"];
                };
            };
        };
    };
    BooksController_list: {
        parameters: {
            query?: {
                /** @description Rows per response, 1–100. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBooks_Output"];
                };
            };
            /** @description `limit` or `offset` is out of range or not a number */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    BooksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book UCI (`BF11`) or slug (`fatawa-islamia-jild-2`). */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book, with page and TOC entry counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail_Output"];
                };
            };
            /** @description No book has that UCI or slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PagesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uci: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page, with previous/next navigation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail_Output"];
                };
            };
            /** @description Not a page UCI — a book or TOC UCI is rejected here */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description No such page */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookPagesController_list: {
        parameters: {
            query?: {
                /** @description Rows per response, 1–100. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Book UCI (`BF11`) or slug (`fatawa-islamia-jild-2`). */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the index */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPageSummaries_Output"];
                };
            };
            /** @description `limit` or `offset` is out of range or not a number */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description No such book */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookPagesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book UCI (`BF11`) or slug (`fatawa-islamia-jild-2`). */
                bookId: string;
                /** @description The REAL PRINTED page number, not a 1-based offset — books in this corpus start anywhere from page 1 to page 179. This is the citation and half of the UCI. */
                pageNo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page, with previous/next navigation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail_Output"];
                };
            };
            /** @description `pageNo` is not a positive integer, or exceeds the frozen 9,999 per-book ceiling */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description No such book, or the book has no such printed page */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    TocController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uci: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry, with parent and children */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TocEntryDetail_Output"];
                };
            };
            /** @description Not a TOC UCI — a book or page UCI is rejected here */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description No such TOC entry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookTocController_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book UCI (`BF11`) or slug (`fatawa-islamia-jild-2`). */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The TOC as a two-level tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TocTree_Output"];
                };
            };
            /** @description No such book */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookTocController_flat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book UCI (`BF11`) or slug (`fatawa-islamia-jild-2`). */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The TOC in reading order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TocFlat_Output"];
                };
            };
            /** @description No such book */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
